add synthetix swaps silver table
FlipsideCrypto/ethereum-models pull request #192
Opened 2022-09-09 02:30 UTC by 0xrdt

add synthetix swaps silver table following the specifications given by Flipside in [this doc](https://docs.google.com/document/d/1kPUehVFgqsiepXbqddXINw_P2Mf4JIFyQ7yQZODQ-qs/edit#)

the logs for the tests covering recency, nulls, duplicates and data type checks can be found below
[test_logs_synthetixs_table.log](https://github.com/FlipsideCrypto/ethereum-models/files/9531812/test_logs_synthetixs_table.log)

2022-09-13 19:42 UTC, desmond-hui requested changes

2022-09-13 19:42 UTC, desmond-hui commented on models/silver/dex/silver_dex__synthetix_swaps.sql
> +        event_inputs :toAmount / 10e18 AS "AMOUNT_OUT",
These amounts don't match etherscan, is it 1 decimal place off?

sample txs:
`0x0948136eb18dbad58640108078910c99ec641d23161366762f377d9e2b094d77`
`0xa69c5ca788a5acf501b425792a2039b081aca101b52d6d674d34826fbd919184`

2022-09-13 19:42 UTC, desmond-hui commented on models/silver/dex/silver_dex__synthetix_swaps.sql
> +    1 = 1
remove

2022-09-13 19:42 UTC, desmond-hui commented on models/silver/dex/silver_dex__synthetix_swaps.sql
> +{% endif %}
This should be part of the 1st CTE `synthetix_swaps_base`

2022-09-13 19:42 UTC, desmond-hui commented on models/silver/dex/silver_dex__synthetix_swaps.sql
> +        1 = 1
These `1 = 1` are not necessary

2022-09-13 19:42 UTC, desmond-hui commented on models/silver/dex/silver_dex__synthetix_swaps.sql
> +                ethereum_community_dev.core.fact_hourly_token_prices
This should be a dbt statement like `{{ ref('table_reference') }}`

2022-09-13 19:42 UTC, desmond-hui commented on models/silver/dex/silver_dex__synthetix_swaps.sql
> +                ethereum_community_dev.core.fact_hourly_token_prices
This should be a dbt statement like `{{ ref('table_reference') }}`

2022-09-13 19:57 UTC, 0xrdt commented on models/silver/dex/silver_dex__synthetix_swaps.sql
> +        event_inputs :toAmount / 10e18 AS "AMOUNT_OUT",
good catch

the amount of decimals is 18, but it should be 1e18 instead of 10e18

2022-09-14 17:10 UTC, desmond-hui requested changes

2022-09-14 17:10 UTC, desmond-hui commented on models/silver/dex/silver_dex__synthetix_swaps.sql
> +                {{ ref('core__fact_hourly_token_prices') }}
This subquery, especially since it is referenced twice, should be moved into it's own CTE and then referenced in the JOIN.  Additionally, add an `is_incremental` condition within the CTE.

I don't think the column aliases are necessary

2022-09-14 17:16 UTC, desmond-hui commented on models/silver/dex/silver_dex__synthetix_swaps.sql
> +                {{ ref('core__fact_hourly_token_prices') }}
incremental condition should be something like...

`where hour >= (select min(swap_hour) from <CTE or TABLE>)`

2022-09-14 22:38 UTC, 0xrdt commented on models/silver/dex/silver_dex__synthetix_swaps.sql
> +                {{ ref('core__fact_hourly_token_prices') }}
it should be max instead of min, right?

2022-09-14 22:49 UTC, desmond-hui commented
It should be min because we want to get all the token prices available that
are greater than the earliest date we need

On Wed, Sep 14, 2022 at 3:39 PM notawizard.eth ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In models/silver/dex/silver_dex__synthetix_swaps.sql
> <https://github.com/FlipsideCrypto/ethereum-models/pull/192#discussion_r971355025>
> :
>
> > +            SELECT
> +                HOUR AS hour_in,
> +                price AS price_in,
> +                token_address AS token_address_in
> +            FROM
> +                {{ ref('core__fact_hourly_token_prices') }}
>
> it should be max instead of min, right?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FlipsideCrypto/ethereum-models/pull/192#discussion_r971355025>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXHUSG2Y266REOKTLQBFBULV6JHYHANCNFSM6AAAAAAQII5DDU>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-09-15 15:25 UTC, desmond-hui requested changes

2022-09-15 15:25 UTC, desmond-hui commented on models/silver/dex/silver_dex__synthetix_swaps.sql
> +            min(block_timestamp)
this should be `min(swap_hour)` otherwise you will get unintended nulls prices because if HOUR = '12:00:00' and Blocktimestamp = '12:01:00' the price would not come through in the filtered hourly prices cte

2022-09-15 15:25 UTC, desmond-hui commented on models/silver/dex/silver_dex__synthetix_swaps.sql
> +    AND hour >= (
the `AND` should be `WHERE`

2022-09-15 22:44 UTC, desmond-hui approved these changes

2022-09-15 22:46 UTC, merged