optimize metadata joins
FlipsideCrypto/ethereum-models pull request #502
Opened 2023-05-05 03:08 UTC by sam-xyz

2023-05-05 03:44 UTC, austinFlipside requested changes

2023-05-05 03:44 UTC, austinFlipside commented on models/silver/silver__nft_transfers.sql
> +        ethereum.silver.nft_labels_temp
Needs jinja

2023-05-05 04:22 UTC, sam-xyz commented on models/silver/silver__nft_transfers.sql
> +        ethereum.silver.nft_labels_temp
added the jinja syntax

2023-05-08 15:55 UTC, drethereum approved these changes

2023-05-08 16:39 UTC, merged