An 1376 sushi lending
FlipsideCrypto/ethereum-models pull request #84
Opened 2022-06-02 21:16 UTC by Vahid-flipside

2022-06-06 21:20 UTC, austinFlipside requested changes
A few things here:

- There are a lot of full table scans on the logs table in this model. Can we explore some ways to do that more efficiently? For example, the first two CTE steps could be one step. You could add the event name column and then just filter for it where you use that CTE elsewhere. Additionally, this step should have incremental logic built in that is only looking for recently ingested tx hashes that meet the event name criteria

- Same goes for the pulls from logs from the main data, I think this could be in one step with some case when statements to account for differences in the two event types

- You should be selecting from the silver logs table here, not the gold view. Selecting from the view basically adds one step to every from statement 

- I also recommend copying the incremental logic I am using in the other `ez_` tables into this model. We often get block / tx data before we return price data from our api. This means that sometimes we load records into the table without a usd price where it should have one. Models need to be set up to heal themselves in this case. The best way to do that is to just pull the last two days or so of ingested data, vs using only records >= max date, on incremental runs. That means that for two days we reload records, and by then should always have the usd price where applicable. Your CTE step from the prices table might need an update to accommodate this logic, I normally just filter for hours that exist in my relevant transaction block times 

- If this is a Kashi lending table, wouldn't the actions be `borrow` and `repay`? I think on the borrowing table we will want to use `deposit` and `withdraw`. Some of the docs will need updates, too

2022-06-08 16:38 UTC, Vahid-flipside commented
Item 1: Added the incremental logic to both of the full scans. 
Item 2: won't be feasible with the current logic since my lending and unlending blocks only look strictly at event_name = 'LogTransfer'. So there won't be any access to other event names to be used in the case statement. 

Item 3 & 4: done

2022-06-08 18:57 UTC, austinFlipside commented
Incremental runs are still not set up correctly. If we ever go three days without filling a missing block, this model will not capture it. If you're querying the core data, you should be using ingested_at like so:
`{% if is_incremental() %}
WHERE
    ingested_at >= (
        SELECT
            MAX(
                ingested_at
            ) :: DATE - 2
        FROM
            {{ this }}
    )
{% endif %}`

For the prices data, you want to only query for data that exist in your base data of interest. You will want to set up the query from the prices table like so:
`{% if is_incremental() %}
AND HOUR :: DATE IN (
    SELECT
        DISTINCT block_timestamp :: DATE
    FROM
        <BASE_DATA>
)
{% endif %}`

This ensure you always get price data for the tokens in your base data, regardless whether or not it was in the last 3 days

2022-06-14 17:21 UTC, austinFlipside approved these changes

2022-06-14 21:34 UTC, austinFlipside approved these changes

2022-06-14 21:35 UTC, merged